version: '3.8'

services:
  trackshows-server:
    container_name: trackshows-server
    build: ./server
    ports:
      - ${DEBUG_PORT}:${DEBUG_PORT}
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
    depends_on:
      - trackshows-db
    networks:
      - trackshows-app
    environment:
      - TRAKT_CLIENT_ID=${TRAKT_CLIENT_ID}
      - TRAKT_CLIENT_SECRET=${TRAKT_CLIENT_SECRET}
      - TRAKT_REDIR_URL=${TRAKT_REDIR_URL}
      - TRAKT_LOGIN_URL=${TRAKT_LOGIN_URL}
    tty: true
    stdin_open: true
  trackshows-client:
    container_name: trackshows-client
    build: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    tty: true
    stdin_open: true
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
    - trackshows-app
  trackshows-db:
    container_name: trackshows-db
    image: postgres
    volumes:
      - ./server/db_data:/data/db
    networks:
      - trackshows-app
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5433:${DB_PORT}'
networks:
  trackshows-app: